DROP DATABASE IF EXISTS COMPANY;

-- DDL: CREATE, ALTER, TRUNCATE, DROP, 
-- [USE, RENAME, SHOW]

-- CREATE DATA BASE
CREATE DATABASE COMPANY;

-- SHOW DATA BASE
SHOW DATABASES;

-- DROP DATA BASE
DROP DATABASE COMPANY;


SHOW DATABASES;
CREATE DATABASE COMPANY;

-- SELECT A DATABASE
USE COMPANY;

-- CREATE TABLE
CREATE TABLE CUSTOMERS
(
	customerid int,
	first_name varchar(20),
	last_name varchar(20),
	country  varchar(20)
);

-- CHECK DEFINITION OF TABLE
DESCRIBE CUSTOMERS;

-- DROP TABLE PERMANENTLY
DROP TABLE CUSTOMERS;

CREATE TABLE CUSTOMERS
(
	customerid int,
	first_name varchar(20),
	last_name varchar(20),
	country  varchar(20) DEFAULT 'India'
);

DESCRIBE CUSTOMERS;

-- ALTER TABLE
-- CHANGE CLAUSE
ALTER TABLE CUSTOMERS
CHANGE LAST_NAME SECOND_NAME VARCHAR(20); -- RENAME COLUMN NAME
DESCRIBE CUSTOMERS;

ALTER TABLE CUSTOMERS
CHANGE SECOND_NAME LAST_NAME VARCHAR(10); -- CHANGE DATATYPE AND COLUMN NAME
DESCRIBE CUSTOMERS;

ALTER TABLE CUSTOMERS
CHANGE COUNTRY COUNTRY VARCHAR(10); -- CHANGE SIZE AND REMOVE CONSTRAINT
DESCRIBE CUSTOMERS;

-- MODIFY CLAUSE
ALTER TABLE CUSTOMERS
MODIFY COUNTRY VARCHAR(15) DEFAULT 'INDIA'; -- MODIFY DATATYPE AND UPDATE CONSTRAINT
DESCRIBE CUSTOMERS;

ALTER TABLE CUSTOMERS
MODIFY CUSTOMERID INT NOT NULL; -- MODIFY COLUMN CONSTRAINT
DESCRIBE CUSTOMERS;

ALTER TABLE CUSTOMERS
MODIFY COUNTRY VARCHAR(10) DEFAULT 'INDIA'; -- MODIFY SIZE WITHOUT CHANGING CONSTRAINT
DESCRIBE CUSTOMERS;

ALTER TABLE CUSTOMERS
MODIFY COUNTRY VARCHAR(15); -- MODIFY SIZE AND REMOVE CONSTRAINT
DESCRIBE CUSTOMERS;

-- ALTER TABLE CUSTOMERS 
-- MODIFY LAST_NAME SECOND_NAME VARCHAR(20); -- CANNOT RENAME COLUMN

-- MODIFY DOES EVERYTHING CHANGE DOES, EXCEPT RENAMING COLUMN

-- ADD CLAUSE
-- ADD COLUMN
ALTER TABLE CUSTOMERS
ADD COLUMN TOTAL_EXP VARCHAR(10);-- ADD NEW COLUMN AT THE END OF TABLE
DESCRIBE CUSTOMERS;

-- ADD, AFTER
ALTER TABLE CUSTOMERS
ADD SALARY INT AFTER LAST_NAME; -- ADD A NEW COLUMN AFTER A SPECIFIC COLUMN
DESCRIBE CUSTOMERS;

-- ADD PRIMARY KEY CONSTRAINT (WITH A CONSTRAINT NAME)
ALTER TABLE CUSTOMERS
ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMERID); -- ADD PRIMARY KEY CONSTRAINT TO EXISTING COLUMN
DESCRIBE CUSTOMERS;

-- DROP CLAUSE
ALTER TABLE CUSTOMERS
DROP COLUMN SALARY; -- DROP A COLUMN
DESCRIBE CUSTOMERS;

-- TRUNCATE TABLE

-- INSERT DATA INTO TABLE
INSERT INTO CUSTOMERS VALUES (101,'Tony','Robbins','INDIA','5');
-- VIEW DATA IN THE TABLE
SELECT * FROM CUSTOMERS;

-- RENAME TABLE
RENAME TABLE CUSTOMERS TO CUSTOMERS_INFO;

-- SHOW ALL TABLES
SHOW TABLES;

-- TRUNCATE => DELETE ONLY DATA BUT NOT TABLE
TRUNCATE TABLE CUSTOMERS_INFO;
SELECT * FROM CUSTOMERS_INFO; -- EMPTY TABLE EXISTS 
DESCRIBE CUSTOMERS_INFO;

-- DROP TABLE
DROP TABLE CUSTOMERS_INFO; -- DROPS TABLE PERMANENTLY ALONG WITH SCHEMA AND DATA
-- DESCRIBE TABLE CUSTOMERS_INFO; -- TABLE DOESNOT EXIST 