-- DML COMMANDS: INSERT, UPDATE, DELETE

USE COMPANY;
SHOW TABLES;
DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE CUSTOMERS
(
	CUSTOMERID INT,
	FIRST_NAME VARCHAR(20),
	LAST_NAME VARCHAR(20),
	COUNTRY VARCHAR(20)
);

DESCRIBE CUSTOMERS;

-- INSERT W.R.T COLUMN NAMES
INSERT INTO CUSTOMERS (CUSTOMERID,COUNTRY,FIRST_NAME,LAST_NAME)
VALUES (1, 'USA', 'MIKE', 'CHRISTENSEN');

SELECT * FROM CUSTOMERS;

DESCRIBE CUSTOMERS;

-- INSERT WITH DEFAULT COLUMN ORDER
-- CHECKS COL DATATYPE AND CONSTRAINT
INSERT INTO CUSTOMERS  
VALUES (2, 'ANDY', 'HOLLANDS', 'AUSTRALIA');

SELECT * FROM CUSTOMERS;

-- COLUMN COUNT DOES NOT MATCH - ERROR
INSERT INTO CUSTOMERS 
VALUES (3, 'SACHIN', 'TENDULKAR');

INSERT INTO CUSTOMERS 
VALUES (3, 'SACHIN', 'TENDULKAR', NULL);

SELECT * FROM CUSTOMERS;

-- INSERT MULTIPLE ROWS DATA
INSERT INTO CUSTOMERS (CUSTOMERID,FIRST_NAME,LAST_NAME,COUNTRY)
VALUES 
(4,'RAVI', 'VEDANTAM', 'INDIA'), 
(5,'TONY', 'ROBBINS', 'UK');

SELECT * FROM CUSTOMERS;

DESCRIBE CUSTOMERS;

-- INSERT DUPLICATE ROW
INSERT INTO CUSTOMERS (CUSTOMERID,FIRST_NAME,LAST_NAME,COUNTRY)
VALUES (5,'TONY', 'ROBBINS', 'UK');

SELECT * FROM CUSTOMERS;

-- UNABLE TO CONSTRAINT AS ITS ALREADY VIOLATED
ALTER TABLE CUSTOMERS
MODIFY CUSTOMERID INT PRIMARY KEY; -- ERROR AS DUPLICATE DATA IS PRESENT

DESCRIBE CUSTOMERS;

-- ADDING OTHER CONSTRAINT WHICH IS NOT VIOLATED
ALTER TABLE CUSTOMERS
MODIFY CUSTOMERID INT NOT NULL;

DESCRIBE CUSTOMERS;

-- VIOLATING CONSTRAINT WHILE INSERTING DATA
INSERT INTO CUSTOMERS (CUSTOMERID, FIRST_NAME,LAST_NAME,COUNTRY)
VALUES (NULL,'TONY', 'ROBBINS', 'UK'); -- ERROR: CUSTOMERID CANNOT BE NULL

-- INSERTING DATA FOLLOWING GIVEN CONSTRAINTS
INSERT INTO CUSTOMERS (CUSTOMERID, FIRST_NAME,LAST_NAME,COUNTRY)
VALUES (6,'IRIS', 'ALLEN', 'USA');

SELECT * FROM CUSTOMERS;

-- UPDATE ONE EXISTING ROW
UPDATE CUSTOMERS
SET FIRST_NAME = 'JOHN'
WHERE CUSTOMERID = 1;

-- SOLVE SAFE UPDATE ERROR
-- SET SQL_SAFE_UPDATES = 0; -- FALSE

SELECT * FROM CUSTOMERS;

-- UPDATE MULTIPLE COLUMNS ON CERTAIN CONDITION
UPDATE CUSTOMERS
SET FIRST_NAME = 'BARRY', LAST_NAME = 'WEST ALLEN', COUNTRY = 'CANADA'
WHERE CUSTOMERID = 5;

SELECT * FROM CUSTOMERS;

-- CAUTION: UPDATE THE DATA FOR ALL ROWS ON NOT GIVING THE CONDITION IN WHERE CLAUSE
UPDATE CUSTOMERS
SET FIRST_NAME = 'TONY', LAST_NAME= 'ROBBINS';

SELECT * FROM CUSTOMERS;

-- DELETE DATA FROM TABLE
DELETE FROM CUSTOMERS WHERE FIRST_NAME='JOHN'; -- NO ROWS ARE DELETED AS NO ROW PRESENT SATISFYING THE CONDITION

DELETE FROM CUSTOMERS WHERE CUSTOMERID = 6; -- DELETES 1 ROW WITH CUSTOMERID 6

DELETE FROM CUSTOMERS WHERE CUSTOMERID = 5; -- DELETES 2 ROWS WITH CUSTOMERID 5

DELETE FROM CUSTOMERS WHERE COUNTRY = NULL; -- '=' WILL NOT WORK WITH NULL : 0 ROWS DELETED

DELETE FROM CUSTOMERS WHERE COUNTRY IS NULL; -- DELETES 1 ROW WITH COUNTRY AS NULL

SELECT * FROM CUSTOMERS; 

-- SAVE RESULT TABLE AS 'data.csv'

-- CAUTION: DELETE ALL ROWS WITHOUT WHERE CONDITION
DELETE FROM CUSTOMERS;

SELECT * FROM CUSTOMERS;

-- TCL COMMANDS: COMMIT, ROLLBACK, SAVEPOINT

SET AUTOCOMMIT = 1; 

INSERT INTO CUSTOMERS (CUSTOMERID,FIRST_NAME,LAST_NAME,COUNTRY)
VALUES  (1,'TONY', 'ROBBINS', 'USA'); 

-- AUTO SAVE IS DONE

SELECT * FROM CUSTOMERS; -- USA

SET AUTOCOMMIT=0; -- DISABLING AUTO COMMIT (AUTO SAVE)

UPDATE CUSTOMERS 
SET COUNTRY='SPAIN'
WHERE CUSTOMERID = 1;

SELECT * FROM CUSTOMERS; -- SPAIN

ROLLBACK; -- ROLLBACK REVERTS CHANGES TO DB => COUNTRY CHANGES FROM SPAIN TO USA

SELECT * FROM CUSTOMERS; -- USA 

COMMIT; -- PERMANENTLY SAVING THE CHANGES IN THE DB

SET AUTOCOMMIT = 1; -- SETTING DEFAULT COMMIT FOR EVERY QUERY

UPDATE CUSTOMERS 
SET COUNTRY='SPAIN'
WHERE CUSTOMERID = 1;

SELECT * FROM CUSTOMERS; -- SPAIN

ROLLBACK; -- ROLLBACK CANNOT REVERT CHANGES AS AUTO COMMIT IS ALREADY DONE AFTER UPDATE

SELECT * FROM CUSTOMERS; -- SPAIN 

-- SAVEPOINT

SET AUTOCOMMIT = 0; -- DISABLING AUTO COMMIT

UPDATE CUSTOMERS 
SET COUNTRY='CANADA'
WHERE FIRST_NAME = 'TONY';

SAVEPOINT A;

UPDATE CUSTOMERS 
SET COUNTRY='INDIA'
WHERE FIRST_NAME = 'TONY';

SAVEPOINT B;

UPDATE CUSTOMERS 
SET COUNTRY='PAKISTAN'
WHERE FIRST_NAME = 'TONY';

SAVEPOINT C;

UPDATE CUSTOMERS 
SET COUNTRY='CHINA'
WHERE FIRST_NAME = 'TONY';

SAVEPOINT D;

SELECT * FROM CUSTOMERS;

-- ROLLBACK; -- ROLLBACKS TO LAST COMMIT 
ROLLBACK TO C; -- ROLLBACKS TO GIVEN SAVE POINT

SELECT * FROM CUSTOMERS; -- pakistan

-- ROLLBACK TO D; -- SAVEPOINT D DOESNOT EXIST

ROLLBACK TO A; -- ROLLBACKS TO GIVEN SAVE POINT

SELECT * FROM CUSTOMERS; -- canada

COMMIT;

SELECT * FROM CUSTOMERS;

ROLLBACK; -- roll back to last commit 

SELECT * FROM CUSTOMERS;

SET AUTOCOMMIT = 1; -- SET AUTO COMMIT TO TRUE FOR EVERY QUERY 