-- SET OPERATIONS

CREATE TABLE EMPLOYEES1 
(
	EMPLOYEE_ID INT (11) UNSIGNED NOT NULL,
	FIRST_NAME VARCHAR(20),
	LAST_NAME VARCHAR(25) NOT NULL,
	SALARY DECIMAL(8, 2) NOT NULL,	
	PRIMARY KEY (EMPLOYEE_ID)
);


INSERT INTO EMPLOYEES1 VALUES (26,'JAGRITI','BAHAL',9000); # ROW IS NOT DUPLICATE W.R.T ROW IN EMPLOYEE TABLE
INSERT INTO EMPLOYEES1 VALUES (27,	'SANG',	'WUU',	4000);
INSERT INTO EMPLOYEES1 VALUES (28,	'JAMIE','LANNISTER',3400);

SELECT * FROM EMPLOYEES1;

-- SET OPERATIONS
-- UNION ALL - LISTS ALL ROWS FROM BOTH TABLES ALONG WITH DUPLICATES ROWS
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES
UNION ALL
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES1;


SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES
UNION 
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES1;

-- UNION WHEN DIFFRENT COLUMNS ARE PRESENT IN DIFFERENT TABLES
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, EMAIL FROM EMPLOYEES
UNION 
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, ' ' FROM EMPLOYEES1;

DROP TABLE EMPLOYEES1;
