USE HR_EMP;

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;

-- EMPS WITH NO DEPT DETAILS
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IS NULL;

-- DEPTS WITH NO EMPLOYEES
SELECT * FROM DEPARTMENTS D 
LEFT JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE E.EMPLOYEE_ID IS NULL;


-- retrieves only the matching rows from both tables
-- ONLY THOSE EMP DETAILS WITH DEPT DETAILS
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, E.DEPARTMENT_ID, E.SALARY, D.DEPARTMENT_NAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID -- INNER JOIN
ORDER BY E.EMPLOYEE_ID;

-- PNLY THOSE DEPTS IN LUCKNOW
SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, D.LOCATION_ID, L.CITY, L.STATE_PROVINCE
FROM DEPARTMENTS D 
INNER JOIN LOCATIONS L
ON D.LOCATION_ID = L.LOCATION_ID
WHERE L.CITY = 'Lucknow';

-- ONLY THOSE EMPS WITH DEPT DETAILS IN LUCKNOW
-- (employee details along with their corresponding department details,
-- but only for employees who belong to a department located in the city of 'Lucknow')
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME,
		E.DEPARTMENT_ID, E.SALARY, D.DEPARTMENT_NAME, 
        L.CITY, L.STATE_PROVINCE
FROM EMPLOYEES E INNER JOIN DEPARTMENTS D 
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
INNER JOIN LOCATIONS L
ON D.LOCATION_ID = L.LOCATION_ID
WHERE L.CITY = 'Lucknow';

-- THOSE EMP WITH THEIR CORRESPONDING DEPT DETAILS
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, D.DEPARTMENT_NAME
 FROM EMPLOYEES E INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;


-- RETRIEVES ALL EMPLOYEE DETAILS WITH OR WITHOUT DEPARTMENT DETAILS
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, D.DEPARTMENT_NAME
 FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;
 
-- LEFT JOIN = LEFT OUTER JOIN
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, D.DEPARTMENT_NAME
 FROM EMPLOYEES E LEFT OUTER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;
 
 
-- RETRIEVES ALL DEPARTMENT DETIALS WITH OR WITHOUT EMPLOYEE DETAILS
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, D.DEPARTMENT_NAME
 FROM EMPLOYEES E RIGHT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- RIGHT JOIN = RIGHT OUTER JOIN
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, D.DEPARTMENT_NAME
 FROM EMPLOYEES E RIGHT OUTER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;


-- FULL JOIN = LEFT UNION RIGHT
-- EMP WITH OR WITHOUT DEPT DETAILS AND DEPTS WITH OR WITHOUT EMPLOYEES
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, D.DEPARTMENT_NAME
 FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
UNION 
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, D.DEPARTMENT_NAME
 FROM EMPLOYEES E RIGHT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;
 
-- FULL JOIN WITH WHERE CLAUSE
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, D.DEPARTMENT_NAME
 FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 WHERE D.DEPARTMENT_NAME LIKE 'H%'
UNION 
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, D.DEPARTMENT_NAME
 FROM EMPLOYEES E RIGHT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
 WHERE D.DEPARTMENT_NAME LIKE 'H%';

-- SELF JOIN: EMPLOYEES FROM SAME DEPARTMENT (AND FILTER BY HUMAN RESOURCE DEPARTMENT (DEPT_ID = 10)
SELECT E.FIRST_NAME, E1.FIRST_NAME, E.DEPARTMENT_ID
 FROM EMPLOYEES E, EMPLOYEES E1 
 WHERE E.DEPARTMENT_ID = E1.DEPARTMENT_ID 
 AND  E.EMPLOYEE_ID <> E1.EMPLOYEE_ID
 AND E.DEPARTMENT_ID = 10;

